[package]
name = "blockstats"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3"  }
futures = "0.3"
subxt = { git = "https://github.com/paritytech/subxt.git", branch = "master" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
